import type { RuntimeApprovalDecision } from '../../../../shared/workflow-run'

const approvalDecisionLabels: Record<RuntimeApprovalDecision, string> = {
  accept: '允许',
  acceptForSession: '在本次会话中允许',
  decline: '拒绝',
  cancel: '取消',
  acceptWithExecpolicyAmendment: '允许并更新执行策略',
  applyNetworkPolicyAmendment: '应用网络策略更新',
  completed: '已完成',
}

export const workflowRunCopy = {
  run: {
    eyebrow: 'Workflow Run',
    backAction: '返回 Project 详情',
    listTitle: 'Workflow Runs',
    listDescription: '从持久状态恢复进行中、等待用户或 blocked 的 Run。',
    count: (count: number) => `${count} 个 Run`,
    empty: '还没有 Workflow Run。',
    runId: (id: string) => `Run ID: ${id}`,
    sourceSnapshot: (source: 'built-in' | 'project', version: string) =>
      `来源快照：${source === 'built-in' ? '内置 Workflow' : 'Project Workflow'}@${version}`,
    currentPhase: (name: string) => `当前 Phase：${name}`,
    blockedReason: (reason: string) => `阻塞：${reason}`,
    recentArtifact: (name: string) => `最近 Artifact：${name}`,
    status: {
      running: '运行中',
      paused: '已暂停',
      waiting: '等待用户',
      blocked: '已 blocked',
      failed: 'Step 失败',
      completed: '已完成',
      skipped: '已跳过',
      cancelled: '已取消',
    },
    activityView: 'Run Activity View',
    progressLabel: 'Run 进度',
    viewMode: '查看模式',
    liveMode: 'Live Mode · 实时跟随',
    inspectionMode: 'Inspection Mode · 检查历史',
    actualPosition: (position: string) => `当前执行：${position}`,
    newActivities: (count: number) => `新增活动 ${count}`,
    returnToLive: '返回实时',
    workflowProgress: 'Workflow 总进度',
    currentProgress: '当前进度',
    ticketHistory: 'Ticket 历史',
    ticketStages: 'Ticket 子流程',
    ticketPosition: (current: number, total: number) => `Ticket ${current}/${total}`,
    ticketTitle: (current: number, total: number, title: string) => `Ticket ${current}/${total} · ${title}`,
    stages: { implementation: '实现', testing: '测试', review: 'Review', commit: 'Commit' },
    finalSummary: 'Workflow Run 最终总结',
    ticketSummary: (title: string) => `Ticket 累计总结：${title}`,
    completedTickets: (count: number) => `已完成 ${count} 个 Ticket`,
    summaryCategories: { implementation: '实现', testing: '测试', review: 'Review', commit: 'Commit', build: 'Build', verification: '验证' },
    summaryFailures: (failed: number, attempts: number) => `失败 attempt ${failed} · 累计 ${attempts} 次 attempt`,
    summaryInterruptions: (count: number) => `中断 ${count} 次`,
    snapshotTitle: '当前 Snapshot',
    phase: (index: number) => `Phase ${index}`,
    step: (index: number) => `Step ${index}`,
    noPending: '无待处理决定',
    pause: '暂停',
    pausing: '正在暂停',
    processing: '正在处理',
    moreActions: '更多 Run 操作',
    composerLabel: 'Run 输入',
    send: '发送',
    sendAndResume: '发送并继续',
    recover: '重试',
    approvalComposerHint: '请在上方审批卡片中选择决定。',
    resume: '继续',
    retry: '重试失败 Step',
    cancel: '结束 Run',
    cancelConfirmTitle: '确认结束 Run？',
    cancelConfirmDescription:
      '结束后不可恢复。当前 Turn 和后续执行将停止，Workspace 修改、历史和 Artifact 均保留，不会回滚或删除。',
    cancelConfirmBack: '返回',
    cancelConfirmAction: '确认结束',
    attempt: (attempt: number) => `attempt ${attempt}`,
    pending: '待执行',
    artifactsTitle: 'Artifact 索引',
    noArtifacts: '当前还没有 Artifact。',
    eventsTitle: 'Workflow Event',
    detailsTitle: 'Step 详情',
    contextTitle: 'Phase Context',
    decisionsTitle: 'Decision Record',
    noDecisions: '当前没有 Decision Record。',
    logsTitle: '执行日志',
    noLogs: '当前没有执行日志。',
    blockerTitle: '阻塞关系',
    conflictResolutionTitle: '冲突处理入口',
    conflictResolutionDescription:
      '请在独立 Workspace 中检查两侧修改后，通过 resolving-merge-conflicts Skill 或 Human Step 处理；Agent Space 不会自动覆盖或合并。',
    conflictResolutionSkill: 'resolving-merge-conflicts',
    conflictResolutionHuman: 'Human Step：确认冲突解决结果后继续 Run',
    availableActionsTitle: '可用操作',
    noAvailableActions: '当前卡片没有可用操作。',
    inputTitle: 'Step 输入',
    outputTitle: 'Step 输出',
    runtimeItemsTitle: '实时 Runtime Item',
    noRuntimeItems: '当前还没有实时 Runtime Item。',
    runtimeTimelineUnavailable:
      '当前无法读取 Runtime Item 历史；已接收的实时更新仍会展示。',
    agentMessageItem: 'Agent 消息',
    finalResponseItem: '最终回复',
    commandItemTitle: '命令执行',
    commandItem: (command: string) => `命令执行：${command}`,
    fileChangeItem: '文件修改',
    expandFiles: '展开文件列表',
    openInIde: '在 IDE 中打开',
    openInIdeError: '没有找到可用的外部 IDE。',
    fileChangeKind: { add: '新增', update: '修改', delete: '删除' },
    editingFile: (path: string) => `Editing ${path}`,
    editedFile: (path: string) => `Edited ${path}`,
    fileChangeCounts: (additions: number, deletions: number) =>
      `+${additions} -${deletions}`,
    diffSummary: (files: number, additions: number, deletions: number) =>
      `${files} 个文件，新增 ${additions} 行，删除 ${deletions} 行`,
    planItem: 'Plan',
    questionItem: '问题',
    questionAnswer: (answer: string) => `回答：${answer}`,
    approvalItem: 'Runtime Approval',
    approvalDecision: (decision: RuntimeApprovalDecision) =>
      `决定：${approvalDecisionLabels[decision]}`,
    interruptItem: '中断',
    interrupting: '正在停止当前 Turn。',
    interrupted: '当前 Turn 已中断。',
    toolItemTitle: 'Tool 调用',
    toolItem: (name: string) => `Tool 调用：${name}`,
    errorItem: '运行错误',
    noCommandOutput: '等待命令输出。',
    fullOutput: '完整输出',
    fullResult: '完整结果',
    commandExitCode: (code: number) => `退出码 ${code}`,
    commandDuration: (durationMs: number) =>
      `耗时 ${Number((durationMs / 1000).toFixed(2))} 秒`,
    runtimeItemStatus: {
      in_progress: '运行中',
      completed: '已完成',
      failed: '失败',
      declined: '已拒绝',
    },
    questionTitle: '待回答问题',
    answerPlaceholder: '输入结构化回答',
    answerAction: '提交回答',
    approvalTitle: 'Approval Gate',
    approveAction: '批准并继续',
    rejectAction: '拒绝并停止',
    noOutput: '暂无输出。',
    noInput: '暂无输入。',
    noError: '没有错误。',
    noContext: '当前 Phase 没有额外上下文。',
    noLocation: '未提供位置',
    projectId: (id: string) => id,
    deliveryTitle: 'Git 交付',
    baseCommit: 'Base Commit',
    branch: '功能分支',
    pullRequest: 'Pull Request',
    checks: 'Checks',
    reviews: 'Reviews',
    mergeability: 'Mergeability',
    noChecks: '尚未返回 checks',
    mergeGateReady: 'Checks、GitHub review 和 mergeability 已满足 Merge Gate。',
    mergeGateBlocked: 'Merge Gate 暂不可批准：',
    deliveryTransferNotice:
      'Data Transfer Notice：External Destination: GitHub；数据：feature branch、commit、Run ID、PR checks 和 review 状态；权限：network.github；断网后从持久化 Pull Request Artifact 恢复。',
    localDelivery: '本地 Git 交付已完成；Project 没有 remote，不会创建 PR。',
    remoteDelivery: 'GitHub delivery 尚未创建 Pull Request。',
  },
} as const
