export const workflowRunCopy = {
  run: {
    eyebrow: 'Workflow Run',
    backAction: '返回 Project 详情',
    listTitle: 'Workflow Runs',
    listDescription: '从持久状态恢复进行中、等待用户或 blocked 的 Run。',
    count: (count: number) => `${count} 个 Run`,
    empty: '还没有 Workflow Run。',
    runId: (id: string) => `Run ID: ${id}`,
    sourceSnapshot: (source: 'built-in' | 'project', version: string) =>
      `来源快照：${source === 'built-in' ? '内置 Workflow' : 'Project Workflow'}@${version}`,
    currentPhase: (name: string) => `当前 Phase：${name}`,
    blockedReason: (reason: string) => `阻塞：${reason}`,
    recentArtifact: (name: string) => `最近 Artifact：${name}`,
    status: {
      running: '运行中',
      paused: '已暂停',
      waiting: '等待用户',
      blocked: '已 blocked',
      failed: 'Step 失败',
      completed: '已完成',
      skipped: '已跳过',
      cancelled: '已取消',
    },
    boardEyebrow: 'Workflow Run',
    runBoardLabel: 'Run Board',
    snapshotTitle: '当前 Snapshot',
    phase: (index: number) => `Phase ${index}`,
    step: (index: number) => `Step ${index}`,
    noPending: '无待处理决定',
    pause: '暂停',
    resume: '继续',
    retry: '重试失败 Step',
    cancel: '取消 Run',
    cancelConfirmTitle: '确认取消 Workflow Run？',
    cancelConfirmDescription:
      '取消后当前 Run 将停止，已保存的 Artifact 和执行记录会保留。',
    cancelConfirmBack: '返回',
    cancelConfirmAction: '确认取消',
    attempt: (attempt: number) => `attempt ${attempt}`,
    pending: '待执行',
    artifactsTitle: 'Artifact 索引',
    noArtifacts: '当前还没有 Artifact。',
    eventsTitle: 'Workflow Event',
    detailsTitle: 'Step 详情',
    contextTitle: 'Phase Context',
    decisionsTitle: 'Decision Record',
    noDecisions: '当前没有 Decision Record。',
    logsTitle: '执行日志',
    noLogs: '当前没有执行日志。',
    blockerTitle: '阻塞关系',
    conflictResolutionTitle: '冲突处理入口',
    conflictResolutionDescription:
      '请在独立 Workspace 中检查两侧修改后，通过 resolving-merge-conflicts Skill 或 Human Step 处理；Agent Space 不会自动覆盖或合并。',
    conflictResolutionSkill: 'resolving-merge-conflicts',
    conflictResolutionHuman: 'Human Step：确认冲突解决结果后继续 Run',
    availableActionsTitle: '可用操作',
    noAvailableActions: '当前卡片没有可用操作。',
    inputTitle: 'Step 输入',
    outputTitle: 'Step 输出',
    runtimeItemsTitle: '实时 Runtime Item',
    noRuntimeItems: '当前还没有实时 Runtime Item。',
    agentMessageItem: 'Agent 消息',
    commandItemTitle: '命令执行',
    commandItem: (command: string) => `命令执行：${command}`,
    fileChangeItem: '文件修改',
    fileChangeCounts: (additions: number, deletions: number) =>
      `+${additions} / -${deletions}`,
    diffSummary: (files: number, additions: number, deletions: number) =>
      `${files} 个文件，新增 ${additions} 行，删除 ${deletions} 行`,
    planItem: 'Plan',
    toolItemTitle: 'Tool 调用',
    toolItem: (name: string) => `Tool 调用：${name}`,
    errorItem: '运行错误',
    noCommandOutput: '等待命令输出。',
    commandExitCode: (code: number) => `退出码 ${code}`,
    commandDuration: (durationMs: number) =>
      `耗时 ${Number((durationMs / 1000).toFixed(2))} 秒`,
    runtimeItemStatus: {
      in_progress: '运行中',
      completed: '已完成',
      failed: '失败',
      declined: '已拒绝',
    },
    questionTitle: '待回答问题',
    answerPlaceholder: '输入结构化回答',
    answerAction: '提交回答',
    approvalTitle: 'Approval Gate',
    approveAction: '批准并继续',
    rejectAction: '拒绝并停止',
    noSelection: '选择一张卡片查看详情。',
    noOutput: '暂无输出。',
    noInput: '暂无输入。',
    noError: '没有错误。',
    noContext: '当前 Phase 没有额外上下文。',
    noLocation: '未提供位置',
    projectId: (id: string) => id,
    deliveryTitle: 'Git 交付',
    baseCommit: 'Base Commit',
    branch: '功能分支',
    pullRequest: 'Pull Request',
    checks: 'Checks',
    reviews: 'Reviews',
    mergeability: 'Mergeability',
    noChecks: '尚未返回 checks',
    mergeGateReady: 'Checks、GitHub review 和 mergeability 已满足 Merge Gate。',
    mergeGateBlocked: 'Merge Gate 暂不可批准：',
    deliveryTransferNotice:
      'Data Transfer Notice：External Destination: GitHub；数据：feature branch、commit、Run ID、PR checks 和 review 状态；权限：network.github；断网后从持久化 Pull Request Artifact 恢复。',
    localDelivery: '本地 Git 交付已完成；Project 没有 remote，不会创建 PR。',
    remoteDelivery: 'GitHub delivery 尚未创建 Pull Request。',
  },
} as const
