export const workflowCopy = {
  workflow: {
    eyebrow: 'Project Workflow',
    viewAction: '查看 Workflow',
    backAction: '返回 Project 详情',
    loading: '正在读取 Workflow...',
    loadError: '读取 Workflow 失败。',
    readOnly: '内置 Workflow 只读',
    projectSource: 'Project Workflow',
    version: (version: string) => `版本 ${version}`,
    origin: (version: string) => `来源：Development Workflow@${version}`,
    directRunAction: '运行',
    copyAction: '复制为 Project Workflow',
    copyError: '复制 Workflow 失败。',
    editAction: '在外部 IDE 中编辑',
    editError: '打开 Workflow File 失败。',
    reloadAction: '重新加载并校验',
    reloadError: '重新加载 Workflow 失败。',
    startAction: '开始运行',
    launchDescription:
      '描述你想推进的想法，开始运行后会从第一步与你一起澄清目标。',
    ideaLabel: '想法',
    ideaPlaceholder: '描述你想做什么、希望解决什么问题',
    preflightAction: '启动检查',
    checking: '正在检查…',
    starting: '正在启动…',
    preflightPassed: '启动检查通过',
    preflightFailed: '启动检查未通过',
    environmentCheckHint: '已检查运行环境和依赖；输入想法后，开始运行时会再次检查。',
    startReady: 'Workflow 已通过启动校验。',
    startError: '无法启动新 Run。',
    validationPassed: '流程校验通过',
    validationFailed: '流程校验失败',
    phaseList: 'Workflow Phase 列表',
    skillPackageEyebrow: '内置 Skill Package',
    skillPackageTitle: '机器可读 Skill Manifest',
    dependencies: '依赖',
    permissions: '权限',
    runtime: 'Runtime',
    stepSkill: 'Skill',
    stepArtifact: 'Artifact',
    stepCondition: 'Condition',
    stepApprovalGate: 'Approval Gate',
    none: '无',
    kind: { skill: 'Skill Step', tool: 'Tool Step', human: 'Human Step' },
  },
} as const
