export const workflowCopy = {
  workflow: {
    eyebrow: 'Project Workflow',
    viewAction: '查看 Workflow',
    backAction: '返回 Project 详情',
    loading: '正在读取 Workflow...',
    loadError: '读取 Workflow 失败。',
    readOnly: '内置 Workflow 只读',
    projectSource: 'Project Workflow',
    version: (version: string) => `版本 ${version}`,
    origin: (version: string) => `来源：Development Workflow@${version}`,
    directRunAction: '直接运行内置 Workflow',
    directRunDescription:
      '无需复制即可运行当前内置版本；创建 Run 时会保存完整 Definition 快照。',
    copyAction: '复制为 Project Workflow',
    copyError: '复制 Workflow 失败。',
    editAction: '在外部 IDE 中编辑',
    editError: '打开 Workflow File 失败。',
    reloadAction: '重新加载并校验',
    reloadError: '重新加载 Workflow 失败。',
    startAction: '启动新 Run',
    preflightEyebrow: 'Run Preflight',
    launchTitle: '输入 Idea，启动 Workflow Run',
    launchDescription:
      '启动前检查 Workspace 和 Project Workflow；检查结果会随 Run 保存。',
    ideaLabel: 'Idea',
    ideaPlaceholder: '描述你想推进的 Idea',
    preflightAction: '运行 Preflight',
    startReady: 'Workflow 已通过启动校验。',
    startError: '无法启动新 Run。',
    validationPassed: 'Workflow Validation 通过',
    validationFailed: 'Workflow Validation 失败',
    phaseList: 'Workflow Phase 列表',
    skillPackageEyebrow: '内置 Skill Package',
    skillPackageTitle: '机器可读 Skill Manifest',
    dependencies: '依赖',
    permissions: '权限',
    none: '无',
    kind: { skill: 'Skill Step', tool: 'Tool Step', human: 'Human Step' },
  },
} as const
